# Notebook Imports

In [22]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.ensemble import RandomForestClassifier 

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
iris = load_iris()

In [8]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

# Build Classification Model

In [28]:
X = iris.data
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
clf = RandomForestClassifier()
clf.fit(X , y )

RandomForestClassifier()

In [21]:
print("R-squared value for training dataset: ", clf.score(X_train, y_train) )
print("R-squared value for testing dataset: ", clf.score(X_test, y_test) )

R-squared value for training dataset:  1.0
R-squared value for testing dataset:  1.0


In [36]:
X[0].shape

(4,)

In [37]:
clf.predict(np.meshgrid(X[0]))

array([0])

In [38]:
clf.predict_proba( np.meshgrid(X[0]) )

array([[1., 0., 0.]])

In [39]:
clf.fit(iris.data, iris.target_names[iris.target])

RandomForestClassifier()

# Data split

In [14]:
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size = 0.2 , random_state = 10 )

In [43]:
clf.fit(X_train, y_train)

RandomForestClassifier()